### ISSUE TITLE
qr_code is not completely secure

### ISSUE THREAD

**Issue by salva** [gryphonshafer/Auth-GoogleAuth#1]
`qr_code` generates an URL pointing to a Google service. That means that Google gets the code, it may be logged in its servers or made public in some unexpected way, or just somebody at Google may be interested in getting it.

A better alternative would be to generate the QR code locally using any of the Perl modules available.

In any case, a notice stating that possible thread should appear in the documentation.

**Comment by gryphonshafer** [comment]
Auth::GoogleAuth doesn't generate QR images by design. Instead, the `qr_code()` method returns a string, and it's up to the caller to decide what to do. The caller can get back from `qr_code()` the otpauth key URI and use whatever means they want to generate the QR image. (As you mentioned, there are several options on CPAN.) Or the caller can request a Google Chart API URL.
